# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181023_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Chinese',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='math',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
